name: Deploy to Pages

on:
  push:
    branches: [atomgit]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          ref: atomgit
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependence
        run: |
          npm install -g pnpm
          pnpm install
          pnpm add sharp
      - name: Build dist
        run: pnpm run build
      - name: Publish branch
        uses: 7emotions/branch-pub@main
        with:
          token: ${{ secrets.ATOM_TOKEN }}
          user: ${{ secrets.ATOM_USER }}
          repo: 7emotions/blog
          github_domain: atomgit.com
          branch: pages
          folder: dist
