name: Deploy to GitHub Pages

on:
  push:
    branches: [atomgit]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          ref: atomgit
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
        with:
          path: . # The root location of your Astro project inside the repository. (optional)
          node-version: 20 # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
          package-manager: pnpm@latest 
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: 7emotions/branch-pub@main
        with:
          token: ${{ secrets.ATOM_TOKEN }}
          user: ${{ secrets.ATOM_USER }}
          repo: 7emotions/blog
          github_domain: atomgit.com
          branch: atom_pages
          folder: dist
